### ISSUE TITLE
PCA coloring incorrect

### ISSUE THREAD

**Issue by DPijnenburg** [tercen/PCA_shiny_operator#3]
We had 4 conditions on wich we colored with 3 replicates each. But the PCA figures did not display the colors correctly.
Biplot tab was also weird.

https://tercen.com/PamgeneEvaluators/w/ebd643c3119c715cacdef627bbe12658/ds/943c638c-b82f-4a5b-9f8d-40fa7853532c/wa

![image](https://user-images.githubusercontent.com/80765307/127462119-7b761037-ef16-4572-8912-b2339c6f053b.png)

![image](https://user-images.githubusercontent.com/80765307/127462186-331b4d69-94d4-4693-9dd2-bc536eddb3ef.png)

**Comment by ginberg** [comment]
hi @DPijnenburg, the issue is not totally clear to me. Could you add the behaviour that you are expecting, i.e. which colors would you expect in the PCA plot? What would you expect in the Biplot? The output that is shown is different than the output in Pamgene or do these issues also exist on Pamgene?

**Comment by Savi235** [comment]
Step 1: Cross Tab view for PCA
![image](https://user-images.githubusercontent.com/62095151/128698451-f7633726-9e09-4bc5-a59e-583594d180f7.png)

Step 2: Colors for A3 and A4 missing! in 3D plot AND Biplot view is wierdly overlapping of samples (below)
![image](https://user-images.githubusercontent.com/62095151/128698552-cfe82def-f542-4ff4-b24f-e731d8eee447.png)
![image](https://user-images.githubusercontent.com/62095151/128698679-5878978a-9238-4f42-a540-66c5bb5368b3.png)

Hope the issue is clear now?

**Comment by Savi235** [comment]
For the previous example:  The Cross Tab view was this one: So, there are 4 conditions and 3 replicates.
You can see that the PCA doesnt colour correctly. Thanks,
![image](https://user-images.githubusercontent.com/62095151/128699917-7e0d4a8a-46ae-461f-a60e-c67b7a9df191.png)

**Comment by ginberg** [comment]
thanks Savi! Yes, I see now that the coloring is not matching in the 3d plot and the biplot is looking weird because of the overlapping. Did you also run the PCA shiny in Bionavigator on this dataset/view? If you could add these charts as well in this issue, it would be very helpful to me.

**Comment by Savi235** [comment]
Hi Ger
Same data (Eg 1 from Dirk: (We both evaluate/ comment together); Shiny PCA using BioNavigator: 3D Plot
![image](https://user-images.githubusercontent.com/62095151/128701493-38394832-17c3-41c0-a881-04453bb30ebf.png)

Same data Shiny PCA using BioNavigator: Bi Plot
![image](https://user-images.githubusercontent.com/62095151/128701583-befb0117-e9c8-4ed0-8712-1c63f4856aec.png)

Hope it helps

**Comment by Savi235** [comment]
You probably have this already but the R source is below, perhaps useful to compare:

##source("C:\\Users\\rdwijn\\Documents\\140-700 Bioinformatics\\pamapps\\components\\Shiny PCA\\impl\\PCA.r")

library(Biobase)
checkpack <- function(packagename){
  if (! (packagename %in% installed.packages() ) ){
    install.packages(packagename, repos = "http://cran.rstudio.com/", dependencies = TRUE)
  }
  library(packagename,character.only = TRUE)
}

if (getRversion() < "3.2"){
		stop("R version 3.2 or higher is required for Shiny PCA version 6 or higher")
}


checkpack("rgl")
checkpack("reshape2")
checkpack("shiny")
checkpack("tcltk")


getPropertyValue <- function(properties=properties, name=name, prop.is.numeric = FALSE) {
	for ( i in 1:length(properties) ) {
		if (properties[[i]][1] == name){
			val = properties[[i]][2]
			if (prop.is.numeric){
				return(as.numeric(val))
			} else {
				return(val)
			}
		}
	}
	stop(paste("property not found: ", name))
	return (NULL)
}

dataFrameOperator <- function(data,properties=properties,folder=folder) {

	metaData <- varMetadata(data)
    grpLabels	 =  colnames(pData(data))[metaData$groupingType=="Color"]
	arrayLabels	 =  colnames(pData(data))[metaData$groupingType=="Array"]
	spotLabels 	 =  colnames(pData(data))[metaData$groupingType== "Spot"]
	aD = pData(data)

	if (length(arrayLabels) > 0){
		obs = droplevels(interaction(pData(data)[arrayLabels]))
	} else {
		stop("PCA requires multiple columns (observations) in he BN cross-tab view")
	}
	
	if (length(spotLabels) > 0){
		vars = droplevels(interaction(pData(data)[spotLabels]))
	} else {
		stop("PCA requires multiple rows (variables) in the BN cross-tab view")
	}
	sampleAnnotation = aD[c(arrayLabels, grpLabels)]
	sampleAnnotation = sampleAnnotation[aD$rowSeq == 1,]
	colorAnnotation = aD[c(grpLabels, arrayLabels)]
	colorAnnotation = colorAnnotation[aD$rowSeq == 1,]
	X = acast(aD,rowSeq~colSeq, value = "val")
	
	X = t(X)	
	if (any(is.na(X))){
		stop("Missing values are not allowed")
	}
	obsNames = obs[aD$rowSeq == 1]
	varNames = vars[aD$colSeq == 1]

	rownames(X) = obsNames
	colnames(X) = varNames
	
	bScale = getPropertyValue(properties, "Scale Spots") == "Yes"
    aPca = prcomp(X,  scale. = bScale)
	
	rm.Comp = getPropertyValue(properties, "Subtract component", TRUE)
	if (rm.Comp > 0){
		N = scale(X, scale = bScale) - (aPca$x[,rm.Comp]) %*% (t(aPca$rotation[,rm.Comp]))
		aPca = prcomp(N, scale. = bScale)
		sVal = melt(N)
	} else {
		sVal = NULL
	}
	
	nComp = min(dim(X)[1], getPropertyValue(properties, "Number of Components", TRUE))
	# reformat and return the required number of loadings and scores
    aFlatRotation = matrix(nrow = dim(aD)[1],ncol = nComp)
    aFlatScore    = matrix(nrow = dim(aD)[1],ncol = nComp)
    for (j in 1:nComp) {
		for (i in 1:dim(X)[2]){
			aFlatRotation[aD$rowSeq == i,j]  = aPca$rotation[i,j]
		}
		for (i in 1:dim(X)[1]){
			aFlatScore[aD$colSeq == i,j]  = aPca$x[i,j]
		}
     }
     aResult = data.frame(aFlatRotation)  
     colnames(aResult) = paste('PC', 1:nComp, sep = '');
     aResult = data.frame(aResult, aFlatScore)
     aNames = colnames(aResult)
     aResult = data.frame(aResult, rowSeq = aD$rowSeq, colSeq = aD$colSeq)     
     aResult = aResult[order(aResult$rowSeq, aResult$colSeq),]
	 if (!is.null(sVal)){
		aResult = data.frame(aResult, sVal = sVal$value)
		edit(aResult)
	 }
	 # store data for showResults
     aRunFile = paste(folder, '\\runData.rda', sep = '')
     
	 
	 aRunDataList = list(aPca = aPca, sampleAnnotation=sampleAnnotation, colorAnnotation = colorAnnotation, varNames = varNames)
     save(file = aRunFile, aRunDataList)
     # exit
     return(aResult) 
}

operatorProperties <- function() {
		propList = list(  	list('Scale Spots', list('No', 'Yes')), 
							list('Number of Components', 5),
							list('Subtract component', 0)
						)    
    return (propList)
}  


showResults <- function(properties=properties, folder=folder) {
    aRunFile = paste(folder, '\\runData.rda', sep = '')
    load(aRunFile)
    aPca = aRunDataList$aPca    
	sAnnotation = aRunDataList$sampleAnnotation
	
	cAnnotation = aRunDataList$colorAnnotation

	varNames = aRunDataList$varNames

   	mxComp = dim(aPca$rotation)[2]
	nComp = min(mxComp, getPropertyValue(properties, "Number of Components", TRUE))
	
	if(mxComp < 3){
		stop("The PCA viewer requires at least 3 components (0bservations)")
	}
	
	px = paste("PC", 1:nComp, sep = "")
	py = px[c(2,1,3:nComp)]
	
	aShinyList = list(ui = pageWithSidebar(
	# Application title
	headerPanel("Shiny PCA scores results"),

	# Sidebar with controls 

	sidebarPanel(
		selectInput("labsOrSpheres", "What to show", 
                choices = c("Text labels", "Spheres")),
		selectInput("colorAnnotation", "Select factor for coloring", choices = colnames(cAnnotation)),
		selectInput("textAnnotation", "Select factor for text labels", choices = colnames(sAnnotation)),
		tags$hr(),
		plotOutput("legend"),
		tags$hr(),
		h5("Shiny PCA", a("help on PamCloud", href="http:///pamcloud.pamgene.com//wiki//Wiki.jsp?page=Shiny%20PCA") ),
		actionButton("stop", "Done")
	),

	# mainpanel
	mainPanel( 
		tabsetPanel(tabPanel("Scores 3D", rglwidgetOutput("scores3D", height = 700, width = 700)),
					tabPanel("Scores Plot matrix",tags$hr(),
								sliderInput("ncomp", "Number of components to show in the matrix.", min = 2, max = mxComp, step = 1, value = nComp),
								tags$hr(),
								plotOutput("mat", height = 700)),
					tabPanel("Biplot", plotOutput("biplot",height = 600, width = 600), 
								sliderInput("showvars", "% largest variable loadings to show",min = 0, max = 100, value = 10 ),
								sliderInput("zl","Zoom variable loadings (%)", min = 1, max = 400, value = 100), 
								selectInput("px", "X-axis", choices = px),
								selectInput("py", "Y-axis", choices = py)),
					tabPanel("Variation", plotOutput("scree"))
		),
		textOutput("done")
	)
	),
	server = function(input, output, session) {
		
		session$onSessionEnded(function() {
		  stopApp();
		  print("Shiny session ended, stopped listening!")
		})
		
		cCol = reactive({
			cHdr = as.character(input$colorAnnotation)
			cGrp = as.factor(cAnnotation[[cHdr]])
			return(1+as.numeric(cGrp))
		})
		
		sLab = reactive({
			tHdr = as.character(input$textAnnotation)
			tGrp = as.character(sAnnotation[[tHdr]])
			return(tGrp)
		})
		
		output$mat <- renderPlot({
			clrs = cCol()
			pairs(aPca$x[,1:input$ncomp], col = clrs, bg = clrs, pch = 21)
		}, height = 650, width = 850)
		
				
		output$scores3D <- renderRglwidget({
			pSym = switch(input$labsOrSpheres, 
				"Text labels" = "p",
				"Spheres" = "s"
			)
			clrs  = cCol()
			tGrp  = sLab()
			open3d()
			plot3d(x = aPca$x[,1],y = aPca$x[,2], z = aPca$x[,3],  col = clrs, box = FALSE, type = pSym, size = 2, xlab = "PC1", ylab = "PC2", zlab = "PC3")
			if(pSym == "p"){
				text3d(x = aPca$x[,1], y = aPca$x[,2], z= aPca$x[,3], texts = tGrp, adj = 0, col = clrs, box = FALSE)
			}
			scene1 = scene3d()
			rgl.close()
			rglwidget(scene1)
		})
		
		output$scree = renderPlot({
			screeplot(aPca, main = "variance explained per component", col = "lightblue")
		})
		
		output$legend = renderPlot({
			plot(1,1, xaxt = "n", yaxt ="n", xlab = "", ylab = "", col = "white", bty = "n")
			cHdr = as.character(input$colorAnnotation)
			cGrp = as.factor(cAnnotation[[cHdr]])
			clrs = unique(cCol())
			legend(x = "top", legend = unique(cGrp), fill = clrs, cex = 1, bty = "n") 
		})
		
		output$biplot = renderPlot({
			xIdx = c(1:nComp)[input$px == px]
			yIdx = c(1:nComp)[input$py == px]
			qntVars = 1-0.01*input$showvars
			zmVars = 0.01 * input$zl;
			oLabs = sLab()
			clrs = cCol()
			idx = c(xIdx, yIdx)
			obs = aPca$x[,idx]
			vars = aPca$rotation[,idx]
			sc = aPca$sdev[idx]^2
			lvars = apply(vars^2, 1, sum)
			bVar = lvars > quantile(lvars, qntVars)
			vars = vars[bVar,]
			xp = c(sc[1]*vars[,1], obs[,1])
			yp = c(sc[2]*vars[,2], obs[,2])
			zm = 1.1
			scxVars = zmVars*sc[1]*vars[,1]
			scyVars = zmVars*sc[2]*vars[,2]
			plot(x = scxVars, y = scyVars, pch = ".", xlim = zm * c(min(xp), max(xp)), ylim = zm * c(min(yp), max(yp)), xlab = input$px, ylab = input$py )
			arrows(x0 = 0, y0 = 0, x = scxVars, y = scyVars, col = "grey")
			text(x = obs[,1], y = obs[,2], oLabs, col = clrs, cex = 2)
			text(x = scxVars, y = scyVars, rownames(vars), col = "black")
		})
		
		done <- reactive({return(input$stop>0)})

		output$done = renderText({
			if(done()){
				stopApp()
				print("Shiny session ended, stopped listening!")
				return("Done")
			} else {
				return("")
			}
		})	
	}
)
	aTry = try(runApp(aShinyList), silent = FALSE)
	if(inherits(aTry, "try-error")){
		#handle the case of an already running shiny app
		stopApp()
		tkmessageBox(message = "Could not start the Shiny service, please retry")
	}
	
}

**Comment by ginberg** [comment]
@Savi235 there was indeed a bug in the operator. I fixed it and put the new version (0.0.2) in your library, can you have a look at it again?

**Comment by Savi235** [comment]
Yay I compared it and it's working now exactly same as in BN. Thanks,
![image](https://user-images.githubusercontent.com/62095151/128839327-7165fab3-a3fe-4c2d-8c7b-3bbde678d709.png)
